galister/wlx-overlay-s

- src/overlays/screen.rs
Requires https://github.com/galister/wlx-capture/pull/1
> Save Pipewire tokens

- src/res/actions_binding_vive.json
- add poses
- set both trackpads to discrete scrolling to prevent scaling from bugging out
> Improve Vive Controller bindings

- src/gui/modular/label.rs
Uptime clock that can be used to replace a clock on the watch like so:
```
- type: Label
rect: [210, 90, 200, 50]
font_size: 24
fg_color: "#99BBAA"
source: Timer
format: "%H:%M" # 23:59
- type: Label
rect: [210, 60, 200, 50]
font_size: 14
fg_color: "#99BBAA"
source: Static
text: "Uptime"
```
> Add uptime timer module

- src/gui/modular/mod.rs
Adds `CenteredLabel` element for config
> Add CenteredLabel

- src/hid/x11.rs
For reference: https://stackoverflow.com/a/70132229
> fix(hid): setup xkb extension before querying keyboard device ID

- src/graphics.rs
Sorry my last pull request seemed to have broken a function used by the uidev feature, this should fix it.
> fixed a compilation error with the uidev feature

- src/gui/canvas/builder.rs
- src/gui/canvas/control.rs
- src/gui/canvas/mod.rs
- src/gui/modular/mod.rs
- src/overlays/keyboard.rs
- src/overlays/toast.rs
- src/res/anchor.yaml
- src/res/settings.yaml
- src/res/watch.yaml
- src/shaders/mod.rs
A proof of concept commit for rounded corners, as mentioned in #55
- ~~No thought to optimization has been done yet~~
- Fixed
- ~~Code needs to be reorganized for readability~~
- Fixed
- ~~Might make keyboard keys invisible (I'm not sure if this is an issue with my build process or my changes)~~
- Fixed
- Breaks existing custom settings.yaml and watch.yaml files, requiring a fifth radius element for every rectangle element
- ~~Adds the radius element directly to the rectangle element, rather than having a separate radius variable, or a specialized rounded rectangle~~
- Fixed
> Rounded Corners Proof of Concept

- Cargo.lock
- Cargo.toml
- src/graphics/mod.rs
fixes freeze with dmabuf capture
> rollback vulkano

- Cargo.lock
- Cargo.toml
- src/backend/input.rs
- src/backend/mod.rs
- src/backend/openvr/mod.rs
- src/backend/openxr/mod.rs
- src/backend/overlay.rs
- src/backend/wayvr/README.md
- src/backend/wayvr/client.rs
- src/backend/wayvr/comp.rs
- src/backend/wayvr/display.rs
- src/backend/wayvr/egl_data.rs
- src/backend/wayvr/egl_ex.rs
- src/backend/wayvr/event_queue.rs
- src/backend/wayvr/handle.rs
- src/backend/wayvr/mod.rs
- src/backend/wayvr/smithay_wrapper.rs
- src/backend/wayvr/time.rs
- src/backend/wayvr/window.rs
- src/graphics/mod.rs
- src/gui/canvas/builder.rs
- src/gui/canvas/control.rs
- src/overlays/keyboard.rs
- src/overlays/mod.rs
- src/overlays/screen.rs
- src/overlays/wayvr.rs
- src/state.rs
This pull request extends wlx's functionality by integrating [WayVR](https://github.com/olekolek1000/wayvr) within the same repository, as an optional `wayvr` feature.
> Integrate WayVR directly into wlx

- .github/workflows/build-appimage.yml
- .github/workflows/build-full.yml
- .github/workflows/build-wayland-openxr-openvr-wayvr.yml
- .github/workflows/make-release.yml
- Cargo.toml
- src/backend/openvr/mod.rs
- src/backend/openxr/mod.rs
- src/backend/task.rs
- src/backend/wayvr/README.md
- src/backend/wayvr/client.rs
- src/backend/wayvr/comp.rs
- src/backend/wayvr/display.rs
- src/backend/wayvr/egl_ex.rs
- src/backend/wayvr/handle.rs
- src/backend/wayvr/mod.rs
- src/backend/wayvr/process.rs
- src/config.rs
- src/config_wayvr.rs
- src/gui/modular/button.rs
- src/gui/modular/mod.rs
- src/main.rs
- src/overlays/wayvr.rs
- src/res/watch.yaml
- src/res/wayvr.yaml
- src/state.rs
The format of the wayvr.yaml configuration file is subject to change at any time.
Example usage in watch.yaml:
```
- type: WayVRLauncher
rect: [0, 200, 400, 36]
corner_radius: 4
font_size: 15
fg_color: "#24273a"
bg_color: "#e590c4"
catalog_name: "default_catalog"
```
Ready to run watch config:
[watch.yaml.zip](https://github.com/user-attachments/files/17449872/watch.yaml.zip)
> WayVR: Initial GUI integration

- README.md
add directions for appimage autostart
> Update Envision section

- src/backend/openvr/mod.rs
- src/backend/openxr/mod.rs
- src/backend/task.rs
- src/backend/wayvr/egl_data.rs
- src/config_wayvr.rs
- src/gui/modular/button.rs
- src/gui/modular/label.rs
- src/gui/modular/mod.rs
- src/overlays/toast.rs
- src/overlays/wayvr.rs
- src/res/watch.yaml
- src/res/wayvr.yaml
Watch: Add "Toggle Dashboard" button by default
Toast: Show user-specific error messages in various places
WayVR: Modify example env vars
> Dashboard button in the watch, Toast error messages

- src/backend/openvr/input.rs
- src/backend/openvr/manifest.rs
- src/backend/openxr/skybox.rs
- src/config.rs
- src/config_io.rs
- src/config_wayvr.rs
- src/gui/modular/mod.rs
- src/overlays/screen.rs
- src/overlays/wayvr.rs
- src/state.rs
config_io: Support `wayvr.conf.d` directory and minor refactoring
WayvR: Read config variables from `wayvr.conf.d`
> WayVR: Modular config support, prepare for Envision integration to install external dashboards

- src/hid/mod.rs
Mouse functionality was breaking for me when using one handle so I have separated it out into two handles.
I think think libevdev doesn't expect one device to output both keyboard and mouse events.
Heres my [discord message](https://discord.com/channels/1065291958328758352/1065335880975388782/1339096070688473120) about it.
> Use separate UInputHandles for mouse and keyboard

- Cargo.lock
- Cargo.toml
- src/backend/osc.rs
- src/backend/wayvr/display.rs
- src/backend/wayvr/mod.rs
- src/backend/wayvr/server_ipc.rs
- src/graphics/mod.rs
- src/gui/canvas/builder.rs
- src/gui/canvas/control.rs
- src/overlays/keyboard.rs
- src/overlays/wayvr.rs
Also fixed various Clippy warnings.
> WayVR IPC: Add `DashboardShown` and `DashboardHidden` events, `WlxInputState` packet

- src/backend/openxr/helpers.rs
> Fix OpenXR IPD calculation

- src/backend/input.rs
- src/backend/openvr/input.rs
- src/backend/openxr/input.rs
- src/backend/openxr/openxr_actions.json5
- src/backend/overlay.rs
- src/backend/wayvr/display.rs
- src/backend/wayvr/mod.rs
- src/gui/canvas/control.rs
- src/gui/canvas/mod.rs
- src/gui/modular/button.rs
- src/hid/mod.rs
- src/overlays/keyboard.rs
- src/overlays/screen.rs
- src/overlays/wayvr.rs
I decided to put in an attempt at implementing #168
This setup works for me on WiVRn and Gnome, and should probably be tested on a few other window managers, as well as other VR setups like Monado and SteamVR
The scroll sensitivity should probably be exposed via a config file, the default values are just what felt good to me
> Switch to WheelHiRes. Add horizontal scrolling

- src/backend/wayvr/mod.rs
- src/backend/wayvr/process.rs
- src/gui/modular/button.rs
- src/overlays/screen.rs
This enables applications to be run via Flatpak or any other wrapper application.
> WayVR: Read the `WAYVR_DISPLAY_AUTH` environment variable from external processes, matching it to our virtual display

- src/res/wayvr.yaml
> WayVR: doc: Rename executable name in the wayvr.yaml

- src/backend/openxr/blocker.rs
- src/backend/openxr/mod.rs
- src/config.rs
Finally, those damn close buttons and other funny things behind your overlay won't be looking so attractive :P
> add basic input blocking through libmonado

- src/backend/wayvr/client.rs
- src/backend/wayvr/comp.rs
- src/backend/wayvr/display.rs
- src/backend/wayvr/egl_data.rs
- src/graphics/mod.rs
Fixes https://github.com/galister/wlx-overlay-s/issues/186
> WayVR: Automatically fallback to software blitting in case if dmabuf initialization has failed

- src/backend/wayvr/handle.rs
- src/backend/wayvr/mod.rs
Use iterators instead of closures
_yeah, it was a skill issue on my end, I was still getting the hang of Rust._
> WayVR: Minor refactoring

- src/backend/notifications_dbus.rs
- src/backend/wayvr/egl_data.rs
- src/backend/wayvr/egl_ex.rs
- src/backend/wayvr/smithay_wrapper.rs
- src/config_wayvr.rs
- src/state.rs
> WayVR: Use eglGetPlatformDisplayEXT if available, cargo clippy warning fixes (Closes #181)

- src/backend/openvr/playspace.rs
- src/backend/openxr/playspace.rs
I haven't tested this on the openvr backend but on openxr it works fine.
Closes #163
> separate floor offset from space drag transform

- src/backend/osc.rs
see: https://wiki.ovrtoolkit.co.uk/#/OSC?id=osc-integration
I haven't tested this, wanted to be lazy and just let gha build it, but its not running actions on my repo. I think this should work though.
> Add OVR Toolkit OSC Parameters
