galister/wlx-overlay-s

Cargo.toml

This should make running and packaging this easier, as dependencies are linked instead of dynamically loaded.

Link native libraries

---

src/backend/overlay.rs

Not elegant solution, but fixes any input positioning issues in the configuration overlay

Fix ui_transform if the aspect ratio of the overlay is <1.0

---

src/overlays/screen.rs

Noticed that a compiler error appeared when compiling without x11 as a feature. With some investigation I discovered that the non x11 create_screens_x11 function was not modified along side the x11 create_screens_x11 function causing the error to occur.

fixed compiling issue for when x11 is not included as a feature

---

src/backend/input.rs
src/backend/openvr/input.rs
src/backend/openxr/input.rs
src/config.rs
src/overlays/screen.rs
src/res/actions.json
src/res/actions_binding_knuckles.json
src/res/actions_binding_oculus.json
src/res/config.yaml

For use when the desktop is configured with window focus following the mouse cursor: with the option enabled and while thouching the joystick, the cursor will not move on the screen allowing for moving both lasers to the keyboard without changing window focus.
I only tested it with OpenVR (SteamVR) and the index controllers, so it would be nice if someone could try it out with the oculus controllers and OpenXR as well.

Add option for focus follows the mouse mode

---

src/config.rs
src/overlays/screen.rs

ignore pw_tokens.yaml when loading files from conf.d, and fix load_pw_token_config

fix: loading pipewire tokens

---

src/backend/openxr/helpers.rs
src/backend/openxr/input.rs

This adds bindings for the original Windows Mixed Reality controllers. I've only tested it with the Lenovo Explorer controllers, but it might work with the Samsung WMR controllers too.
Edit: added (untested) bindings for HP Reverb G2 controllers.
Edit: This works mostly with my controllers, but the scrolling is reversed and the existing deadzone isn't large enough so it isn't really usable.

Add bindings for WMR controllers

---

Cargo.lock
Cargo.toml
src/backend/openxr/helpers.rs
src/backend/openxr/input.rs
src/backend/openxr/mod.rs
src/backend/openxr/playspace.rs

Cleaned up https://github.com/galister/wlx-overlay-s/pull/40 so that it doesn't break on un-patched Monado and WiVRn.
Monado playspace mover branch by Rin: https://gitlab.freedesktop.org/RinLovesYou/monado
Those who need Playspace mover with Vive trackers: https://github.com/galister/wlx-overlay-s/pull/40#issuecomment-2122842036
When using Monado, WlxOverlay-S will automatically find libmonado.so and initialize the playspace mover, if the Monado version is compatible.
On WiVRn, I did not have luck getting it to work myself, but the following extra steps are needed, in case you want to test:
- in the server build folder, `ninja libmonado.so`
- export the absolute path of that as `LIBMONADO_PATH` when launching WlxOverlay-S

feat(openxr): Monado playspace mover

---

README.md

Some parts of the existing documentation were a bit confusing. This PR attempts to fix some areas that may have been unclear or awkward
In addition to this PR, I have also made some modifications to the wiki pages, which can be found here: https://github.com/AdalynBlack/wlx-overlay-s-wiki/commit/da1aa0bfd49d991528a04de7645508393ef0d588
Unfortunately, GitHub doesn't allow me to PR the wiki, so this was my solution to that issue

Documentation Clarity Improvements

---

src/backend/openxr/mod.rs

Fixes .unwrap() panic in the simulated Monado driver

Input source: Update monado devices only if they are available

---

src/overlays/mirror.rs

Now spawns directly in front of head. `(0, 0.5, -0.5)` could have been one fix, but the default of `(0, 0, -1)` seems ok too.

Fix mirrors spawning behind head

---

src/backend/input.rs
src/backend/openxr/input.rs
src/backend/openxr/openxr_actions.json5
src/backend/openxr/playspace.rs

On index if you double click the left touchpad, you'll reset the playspace offset. This is faster than having the config panel open.
It runs first in the update function so that the second click to reset doesn't count as an attempt to start another playspace drag. For that, you must press it a third time.

feat: XR binding for playspace reset

---

build.rs

Adds `--always` to force git to return the version hash if no tags are available
Avoids the error `fatal: No names found, cannot describe anything.` on forked repositories that don't have any release tags

Use git hash if no tags can be found

---

contrib/wlx-overlay-s.service

Using this service file, we can autostart wlx-overlay-s alongside Monado's systemd service.
A packager should substitute `@prefix@` with the installation prefix of the binary and place the file in one of systemd's user services directories (i.e. `/usr/share/systemd/user/`).
Users can then make sure the service is enabled using `systemctl --user enable wlx-overlay-s.service` and just start Monado using `systemctl --user start monado.service`.

contrib: add systemd service for Monado autostart

---

src/config_wayvr.rs
src/overlays/wayvr.rs
src/res/wayvr.yaml
src/state.rs

This PR allows for the launch of the WayVR app immediately after wlx startup, via setting `shown_at_start` app parameter to `true` (see wayvr.yaml).

WayVR: `shown_at_start` app param support

---

src/backend/wayvr/comp.rs
src/backend/wayvr/display.rs
src/backend/wayvr/mod.rs

This greatly decreases GPU usage while displaying a static or rarely updating content.

WayVR: Redraw only if needed

---

src/backend/openvr/mod.rs
src/backend/openxr/mod.rs
src/backend/wayvr/client.rs
src/backend/wayvr/display.rs
src/backend/wayvr/mod.rs
src/backend/wayvr/process.rs
src/config_wayvr.rs
src/overlays/wayvr.rs
src/res/wayvr.yaml
src/state.rs

- Support for foreign wayland clients, WayVR process is now separated into managed and external one
- Add `run_compositor_at_start` global param
- Add `primary` display param
- Export WAYLAND_DISPLAY number into XDG_RUNTIME_DIR directory
- Bugfix: Redraw event is not triggered after despawning a process
- Sanitization in WayVRConfig::post_load()

WayVR: External process support, various tweaks and bugfixes

---

src/overlays/keyboard.rs
src/res/keyboard.yaml

This patch adds the ability to apply the CTRL modifier when pressing keys on the keyboard while the purple laser is active.

Enable modifier key with purple laser

---

src/backend/wayvr/display.rs
src/backend/wayvr/mod.rs
src/config_wayvr.rs
src/overlays/wayvr.rs
src/res/wayvr.yaml
src/state.rs

This PR allows the user to configure auto-hide delay in case if no window is present. Very useful in cases when the user closes a window.

WayVR: Display auto-hide support (Closes #98), keyboard settings in config

---

src/backend/openvr/mod.rs
src/backend/openxr/mod.rs
src/backend/osc.rs

I've edited the osc.rs file to send HMD, controller, and tracker battery levels and charging state over OSC to VRChat.
It takes in AppState as a new parameter, but could probably pass just the raw list of devices unless we want to add more parameters like FPS or IPD, etc.
For now there is a workaround for HMD battery specifically as XSOverlay has no parameter for it, and OVR Toolkit uses an int 0-100. I implement both 0-100 as hmdBattery and 0-1 as headsetBattery.
I can only test the HMD battery on Monado at the moment (WiVRn with PICO 4), so controller batteries, tracker batteries, and SteamVR devices are untested.
Parameters are based on the XSOverlay format, excluding average battery levels but adding charging state. Charging state in my testing is delayed, I expect it only updates …

Send device battery levels over OSC

---

src/backend/osc.rs

Adds parameters for `averageTrackerBattery` and `averageControllerBattery`.
As before, these are untested since I have no trackers and use WiVRn.
Might want to write some documentation for the OSC parameters, too. Let me know where I should put it and I'll do that if I can.

OSC: Finish XSOverlay parity

---

Cargo.lock
Cargo.toml
src/backend/wayvr/comp.rs
src/backend/wayvr/mod.rs

Fixes crash for webkitgtk apps.
We can finally run a fully accelerated WayVR Dashboard :fire::fire:

WayVR: Add dmabuf (backend_drm) to the compositor

---

com.github.galister.wlx-overlay-s.json

I made a typo on envision, I spelled `launch_opts` as `luanch_opts`. This PR renames it with the typo, and adds the duplicate key `args`, as I've decided to rename it on envision

fix: launch_opts to luanch_opts and args

---

Cargo.lock
Cargo.toml
src/backend/input.rs
src/backend/openxr/lines.rs
src/backend/openxr/overlay.rs
src/backend/openxr/skybox.rs
src/backend/overlay.rs
src/backend/wayvr/display.rs
src/backend/wayvr/egl_data.rs
src/backend/wayvr/mod.rs
src/backend/wayvr/server_ipc.rs
src/overlays/wayvr.rs

Wlx:
```
- Fix compilation warnings
```
WayVR:
```
- IPC: Add `WvrDisplaySetVisible` and `WlxHaptics`
- Do not pass width and height to `eglCreateImage`
- Set dashboard larger and further a bit
- Bump dashboard resolution from 960x540 to 1920x1080
```
WayVR Dashboard (version 0.1.1):
```
- Haptics feedback on button enter and down/up
- Hide created display by default
- Automatically show hidden display after spawning a process
- DisplayOptions: "Show"/"Hide" button
- DisplayList: Refresh display list directly after changing its state
- Auto-scale content to window size (16:9, centered). 100% resolution at 960x540.
- Exclude `wayvr_dashboard` from the process list, probably nobody wants to close it permanently
```

WayVR: Improvements (WayVR Dash 0.1.1)

---

src/backend/openvr/mod.rs
src/backend/openxr/mod.rs
src/backend/osc.rs
src/gui/modular/button.rs
src/state.rs

Just adds an action to buttons that sends a Float to an address over OSC. (e.g. to control a VRChat avatar, or some other OSC application)
I've just implemented it with `OscType::Float` for now since it can represent Float, Int, and Bool. (at least for VRChat)
Unsure if making separate actions for each type or trying to handle the type internally somehow (`type: float` or `float_value: 3.5`) is better. (in draft for feedback)
```
click_down:
- type: SendOSCFloat
parameter: "/avatar/parameters/button1"
value: 1
click_up:
- type: SendOSCFloat
parameter: "/avatar/parameters/button1"
value: 0
```
It also merges the OSC client creation from openxr.rs and openvr.rs into state.rs `state.app`, and makes osc.rs `send_params()` take in a list of devices instead of `app_state` itself, since I was …

Add UI button actions to send arbitrary OSC values.

---

Cargo.lock
Cargo.toml
src/backend/openvr/mod.rs
src/backend/openxr/mod.rs
src/backend/wayvr/display.rs
src/backend/wayvr/mod.rs
src/backend/wayvr/process.rs
src/backend/wayvr/server_ipc.rs
src/backend/wayvr/window.rs
src/overlays/wayvr.rs

```
WayVR:
- Layouting system (tiled and stacked)
IPC:
- Implemented routes: `WvrDisplaySetWindowLayout`, `WvrDisplayWindowList`, `WvrWindowSetVisible`, `WvrProcessGet`,
- Packet broadcasting
- State change feedback to the client (displays/windows/processes)
```

WayVR: Layouting system, state changing feedback, process userdata, various IPC changes

---

contrib/wayvr/watch_wayvr_example.yaml

The WayVR example config doesn't have a dashboard toggle button. This simply adds that button to the example config

Add "Toggle Dashboard" button to the WayVR example watch config

---

Cargo.lock
Cargo.toml
src/config_wayvr.rs
src/main.rs

Terminal output:
/tmp/wlx.log output (compact):
[tracing-subscriber crates.io](https://crates.io/crates/tracing-subscriber). It doesn't use Tokio, so it's lightweight.

Wlx: Use tracing-subscriber for logging instead of env-logger

---

.github/workflows/make-release.yml

In order to ease writing a Gentoo ebuild, this bundles all the crates (except git ones) into a single tar.xz.
I have not been able to test the release step as it seems I need to setup secrets, CI did however build the tarball when testing on my fork.

CI step to generate a tarball of crates

---

src/backend/openxr/openxr_actions.json5

Currently, only the Index controllers have a space_reset binding by default, bound to the space_drag binding's double click
I've copied that same logic over to all controllers so that all controllers have a default space_reset binding

Add default space_reset binding for all controllers

---

src/res/wayvr.yaml

WayVR Dashboard doesn't need this environment variable anymore since version 0.3.3, it's set automatically.
[skip ci]

WayVR: Update wayvr.yaml

---

src/backend/openxr/helpers.rs
src/backend/openxr/input.rs
src/backend/openxr/openxr_actions.json5

This PR restores the old default dpad bindings for click modifiers (dpad up for right click and dpad down middle click). Those bindings were removed in commit b8a0e36. 
This PR also binds the show_hide, space_drag, and space_rest actions to the system buttons, which doesn't interfere with the menu bindings in most games.
The OpenXR dpad binding extension is currently broken in upstream Monado, I'm looking into this.
The OpenXR dpad binding extension only allows binding to touchpad clicks and not to trackpad touches, so this conflicts more often with other applications than the default Quest bindings. I still think having these buttons work is better than not having them at all.

Improve default WMR OpenXR bindings

---

wlx-overlay-s.desktop

WiVRn now parses .desktop files and uses the X-WiVRn-VR category to filter applications it should show.

Add X-WiVRn-VR category in .desktop file

---

uidev/src/testbed/testbed_generic.rs
wgui/doc/widgets.md
wgui/src/drawing.rs
wgui/src/parser/component_button.rs
wgui/src/parser/component_checkbox.rs
wgui/src/parser/component_slider.rs
wgui/src/parser/mod.rs
wgui/src/parser/style.rs
wgui/src/parser/widget_div.rs
wgui/src/parser/widget_label.rs
wgui/src/parser/widget_rectangle.rs
wgui/src/parser/widget_sprite.rs
wgui/src/renderer_vk/context.rs
wgui/src/renderer_vk/text/mod.rs
wgui/src/renderer_vk/text/text_renderer.rs
wgui/src/widget/label.rs
wgui/src/widget/sprite.rs
wlx-overlay-s/src/assets/gui/watch.xml
wlx-overlay-s/src/gui/panel/button.rs
wlx-overlay-s/src/gui/panel/label.rs
wlx-overlay-s/src/overlays/keyboard/builder.rs

Instead of doing `iter_attribs` inside the parser of each element type (and sometimes multiple times per element), pre-process attributes once per element and store the results.
To keep to `Rc<str>` and avoid string copies, the custom attribs keys are back to being reported with the leading `_` included.

attribs rework
